### ISSUE TITLE
Consider whether to have a TODO file, or to just use issues to track what needs to be done.

### ISSUE THREAD

**Issue by AdrianKoshka** [makruger/website-2.0#7]
While a TODO file is nice, as we can mark it off and keep it updated and such.
I think we should considering possibly using issues.

@shaggytwodope @makruger

**Comment by AdrianKoshka** [comment]
TODO

 - [ ] Convert docs in [docs/notes/](https://github.com/makruger/website-2.0/tree/master/docs/notes) from ``asciidoctor`` to ``markdown``.
 - [ ] make a CLA(Contributors License Agreement.)
 - [ ] Setup [travis](travis-ci.org) (probably via PR)
 - [ ] Fix typos

**Comment by shaggytwodope** [comment]
Tracking with individual issues is great imo. Either way works for me.

**Comment by makruger** [comment]
Could do both....that is have a TODO file and discussing it via issues.

**Comment by AdrianKoshka** [comment]
sounds good
